### ISSUE TITLE
add possibility select SSTV mode and PD mode

### ISSUE THREAD

**Issue by sp2ong** [AgriVision/pisstv#3]
Hi,

It will be nice to possibility select different modes SSTV like:

https://github.com/hatsunearu/pisstvpp

and ad one more mode PD120 which allow send images with size 640x480

http://www.classicsstv.com/pdmodes.php

**Comment by AgriVision** [comment]
I consider https://github.com/hatsunearu/pisstvpp as a worthy successor to my project.
No plans yet for PD120.
